# GitHub Sponsors funding configuration
github: [Shadowwalker0P]

# Additional funding options
# custom: ['https://paypal.me/yourname']
# patreon: 'yourname'
# ko_fi: 'yourname'
# liberapay: 'yourname'
# buy_me_a_coffee: 'yourname'
# issuehunt: 'yourname'
# otechie: 'yourname'
